# Overview of Numpy

In [1]:
import numpy as np

In [2]:
[1, 2, 3] * 2

[1, 2, 3, 1, 2, 3]

In [3]:
old_list = [1, 2, 3]
new_list = []
new_list.append(old_list[0] * 2)
new_list.append(old_list[1] * 2)
new_list.append(old_list[2] * 2)
new_list

[2, 4, 6]

In [4]:
old_list = [1, 2, 3]
new_list = []
for el in old_list:
    new_list.append(el * 2)
    
new_list

[2, 4, 6]

In [8]:
new_list = [y * 2 for y in old_list]
new_list

[2, 4, 6]

In [6]:
new_list = list(map(lambda x: x * 2, old_list))
new_list

[2, 4, 6]

In [10]:
data = np.array([1 ,2, 3])
data * 2

array([2, 4, 6])

In [13]:
list(range(2, 5))

[2, 3, 4]

## Numpy is Fast!

In [16]:
%%timeit
[el * 2 for el in list(range(1_000_000))]

93.4 ms ± 2.95 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [17]:
%%timeit
np.arange(1_000_000) * 2

3.2 ms ± 41.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Exploring Arrays

In [18]:
data = np.arange(12)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
data.dtype

dtype('int64')

In [20]:
data.astype(float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [21]:
data.astype(np.float32)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
      dtype=float32)

In [22]:
data.dtype

dtype('int64')

In [23]:
data2 = data.astype(float)
data2.dtype

dtype('float64')

In [26]:
np.append(data, 22)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 22])

In [31]:
%%timeit
data = list(range(10000))
new_data = []
for el in data:
    new_data.append(el)
    

738 µs ± 26 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [32]:
%%timeit
data = np.arange(10000)
new_data = np.array([])
for el in data:
    new_data = np.append(new_data, el)

56.6 ms ± 654 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [34]:
data = np.arange(12)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
len(data)

12

In [40]:
data.size

12

In [41]:
data.shape

(12,)

In [43]:
data2 = data.reshape(3, 4)
data2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
data2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [46]:
data2.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [47]:
np.transpose(data2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [50]:
np.transpose(
    [[1, 2],
     [3, 4]]
)

array([[1, 3],
       [2, 4]])

In [52]:
np.mean(data)

5.5

In [53]:
np.std(data)

3.452052529534663

In [54]:
np.max(data)

11

In [55]:
np.linalg.norm(data)

22.494443758403985

In [57]:
np.max(data2, axis=0)

array([ 8,  9, 10, 11])

In [59]:
np.mean(data2, axis=0)

array([4., 5., 6., 7.])

In [63]:
np.mean(data2, axis=0, keepdims=True)

array([[4., 5., 6., 7.]])

In [58]:
np.mean(data2, axis=1)

array([1.5, 5.5, 9.5])

In [65]:
np.mean(data2, axis=1, keepdims=True)

array([[1.5],
       [5.5],
       [9.5]])

In [67]:
np.mean(np.matrix(data2), axis=1)

matrix([[1.5],
        [5.5],
        [9.5]])

In [71]:
np.random.randint(1, 10, size=[5, 5])

array([[8, 1, 8, 7, 8],
       [8, 4, 4, 6, 6],
       [5, 4, 9, 5, 7],
       [4, 8, 7, 4, 2],
       [4, 9, 5, 8, 2]])