# Booleans: Declaring Something to Be True or False


## Truthyness / Falsyness

Python values are **Falsy** if:

  - It is a number that is equal to 0.
  
  - It is a boolean that is equal to False.
  
  - It is a collection that is empty.
  
  - It is None.

To find out if a Python object is **Truthy** or **Falsy**, simply convert it to a **bool** type using the **bool()** constructor function:

``` python
>>> bool(3)
True
```


**Exercises**: Are each of the values in the code cells below **Truthy** or **Falsy**?  

In [1]:
bool(3)

True

In [2]:
0

0

In [3]:
30

30

In [4]:
-3

-3

In [5]:
0.1

0.1

In [6]:
0.0

0.0

In [7]:
True

True

In [8]:
False

False

In [9]:
not False

True

In [10]:
not "Nick"

False

In [14]:
not "Trump"

False

In [15]:
"True"

'True'

In [16]:
"False"

'False'

In [17]:
None

In [18]:
[1, 2, 3]

[1, 2, 3]

In [19]:
[False]

[False]

## Casting Arrays to Logical Values

When working with large sets of data, we often care more about whether each of the individual values inside the array are truthy or falsy, rather than whether the entire array is truthy or falsy.  This is most-often done using the **comparison operators** (>, <, ==, !=, >=, <=). 

*Note*: This only works with Numpy arrays.  To perform the same conversion on each element of a list, you would either use a for-loop and build a new list of bools using the append() pattern (as seen previously in the "Iteration.ipynb" notebook), or convert it first to a Numpy array using the **np.array()** constructor function.

**Exercises**: Make arrays of True/False values that answer the following questions about the dataset below for each element.

In [23]:
import numpy as np

list_of_values = [3, 7, 10, 2, 1, 7, 20, -5]
data = np.array(list_of_values)

1. Which values are greater than zero?

In [24]:
data > 0

array([ True,  True,  True,  True,  True,  True,  True, False])

2. Which values are equal to 7?

In [25]:
data == 7

array([False,  True, False, False, False,  True, False, False])

3. Which values are greater or equal to 7?

In [26]:
data >= 7

array([False,  True,  True, False, False,  True,  True, False])

4. Which values are not equal to 7?

In [27]:
data != 7

array([ True, False,  True,  True,  True, False,  True,  True])

## Logical Indexing

If an array of True/False values is used to *index* another array, and both arrays are the same size, it will return all of the values that correspond to the True values of the indexing array.

**Example:**

In [28]:
data = np.arange(6)
data

array([0, 1, 2, 3, 4, 5])

In [29]:
is_big = data > 3
is_big

array([False, False, False, False,  True,  True])

In [30]:
data[is_big]

array([4, 5])

**Exercises**:  Using the data below, extract only the values that corresspond to each question

In [31]:
data = np.array([3, 1, -6, 8, 20, 2, 7, 1, 9, 7, 7, -7])
data

array([ 3,  1, -6,  8, 20,  2,  7,  1,  9,  7,  7, -7])

1. The values that are less than 0

In [32]:
data[data < 0]

array([-6, -7])

2. The values that are greater than 3

In [33]:
data[data > 3]

array([ 8, 20,  7,  9,  7,  7])

3. The values equal to 7

In [34]:
data[data == 7]

array([7, 7, 7])

4. The values not equal to 7

In [35]:
data[data != 7]

array([ 3,  1, -6,  8, 20,  2,  1,  9, -7])

  5. The values equal to 20

In [39]:
data[(data == 20) | (data == 5)]

array([20])

In [41]:
8 > 5 and 2 < 6

True

In [46]:
if 3 & 6:
    print(True)

True


In [47]:
3 and 6

6

In [48]:
0 and 6

0

In [49]:
4 or 5

4

In [51]:
0 or 6

6

In [53]:
6 and 0

0

In [57]:
(data == 7) & (data == 3)

array([False, False, False, False, False, False, False, False, False,
       False, False, False])

## Extra Exercises

Using the following dataset, have Python to calculate the answers to the questions below:

In [58]:
data = np.array([3, 1, -6, 8, 20, 2, 7, 1, 9, 7, 7, -7])
data

array([ 3,  1, -6,  8, 20,  2,  7,  1,  9,  7,  7, -7])

1. How many values are greater than 4 in this dataset?  (*Hint:* the len() function is useful here)

In [60]:
len(data[data > 4])

6

In [61]:
sum(data > 4)

6

2. How many values are equal to 7 in this dataset?

In [62]:
len(data[data == 7])

3

In [63]:
sum(data == 7)

3

3. What is the mean value of the positive numbers in this dataset?

In [65]:
np.mean(data[data > 0])

6.5

In [66]:
data[data > 0].mean()

6.5

4. What is the mean value of the negative numbers in this dataset?

In [67]:
np.mean(data[data < 0])

-6.5

In [68]:
data[data < 0].mean()

-6.5

5. What proportion of the values in this dataset are positive?

In [69]:
len(data[data > 0]) / len(data)

0.8333333333333334

In [71]:
(data > 0).mean()

0.8333333333333334

6. What proportion of the values in this dataset are less than or equal to 8?

In [72]:
np.mean(data <= 8)

0.8333333333333334